name: pokemon_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  go_router: ^16.0.0
  flutter_native_splash: ^2.4.1
  flutter_bloc: ^8.1.6
  dio: ^5.4.3+1
  dio_cache_interceptor: ^3.4.4
  dio_cache_interceptor_hive_store: ^3.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  fluttertoast: ^8.2.6
  cached_network_image: ^3.3.1
  get_it: ^7.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/pokeball.png
    - assets/images/splash.png

flutter_native_splash:
  color: "#EE1515"
  image: "assets/images/splash.png"
  android_gravity: center
  ios_content_mode: center
  android_12:
    color: "#EE1515"
    image: "assets/images/splash_android.png"
  web: false

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/pokeball.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color_ios: "#FFFFFF"
